version: '3'

services: 
  webserver:
    image: wesleywillians/domingao-fc:latest
    ports:
      - "80:8080"
    deploy:
      mode: replicated
      replicas: 5
      restart_policy: 
        condition: on-failure
      
