version: '3'

services: 
  webserver:
    image: wesleywillians/esquenta4-webserver
    ports:
      - "80:8080"
    deploy:
      mode: replicated
      replicas: 7
      restart_policy: 
        condition: on-failure
      
