---
- hosts: all
  become: yes
  roles:
    - role: install-docker

- hosts: manager
  become: yes
  roles:
    - role: setup-swarm-manager 

- hosts: managernodes
  become: yes
  roles:
    - role: add-secundary-manager 

- hosts: worker
  become: yes
  roles:
    - role: add-worker    

- hosts: manager
  become: yes
  roles:
    - role: deploy-stack