name: Deploy
on:
  push:
    branches: [main]

jobs:
  terraform-plan:
    name: Plan Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init -input=false

      - name: Terraform validation
        run: terraform validate

      - name: Terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform plan -input=false  

  deploy-terraform:
    name: Apply Terraform
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment:
      name: deploy
      url: ${{ steps.step_id.outputs.url_output }}
    steps:
    - uses: actions/checkout@v1

    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform init -input=false

    - name: Terraform validation
      run: terraform validate

    - name: Terraform apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform apply -auto-approve -input=false      
      
    - name: Sleep for 30s
      uses: juliangruber/sleep-action@v1
      with:
        time: 30s

  deploy-ansible:
    name: Deploy ansible
    needs: deploy-terraform
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: generate secret cert for ansible
      run: |
          echo ${{ secrets.ANSIBLE_SECRET_FILE }} | base64 -d > ansible/swarm.cer
          chmod 400 ansible/swarm.cer
      shell: bash

    - name: run ansible playbook
      run: |
        cd ansible
        ansible-playbook main.yaml
